export enum USER_ROLES {
    SUPERADMIN = 'SUPERADMIN' ,
    CONSUMER = 'CONSUMER' ,
    BOARD_MEMBER = 'BOARD_MEMBER' ,
    BOARD_ADMIN = 'BOARD_ADMIN' ,
    SUPERVISOR = 'SUPERVISOR' ,
    FIELD_WORKER = 'FIELD_WORKER'
};
